name: Publish to Registry

on:
  push:
    branches:
      - master 

  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: my-step
        run: echo "Hello World!"

  deploy_dev:
    name: Deploy Development
    needs: build_docker_image
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://inspex.dev.designerpages.com

    steps:
      - name: my-step
        run: echo "Hello World!"
        
  deploy_staging:
    name: Deploy Development
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://inspex.dev.designerpages.com

    steps:
      - name: my-step
        run: echo "Hello World!"

  deploy_prod:
    name: Deploy Production
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://inspex.dev.designerpages.com

    steps:
      - name: my-step
        run: echo "Hello World!"
