name: Publish to Registry

on:
  push:
    branches:
      - master 

  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build_docker_image:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: my-step
        run: echo "Hello World!"

  deploy_dev:
    name: Deploy Development
    needs: build_docker_image
    runs-on: ubuntu-latest
    environment:
      name: dev
      url: https://localhost:8080

    steps:
      - name: my-step
        run: echo "Hello World!"

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: always() # Pick up events even if the job fails or is canceled.

  deploy_staging:
    name: Deploy Development
    needs: deploy_dev
    runs-on: ubuntu-latest
    environment:
      name: staging
      url: https://localhost:8080

    steps:
      - name: my-step
        run: echo "Hello World!"

  deploy_prod:
    name: Deploy Production
    needs: deploy_staging
    runs-on: ubuntu-latest
    environment:
      name: prod
      url: https://localhost:8080

    steps:
      - name: my-step
        run: echo "Hello World!"
